version: '3.7'
services:
  bookstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: db_password
  postgres:
    image: postgres:12.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./db-data:/var/lib/postgresql/data
